### PR TITLE
[II-126]: Change the data storage to not be a gigantic hash in a script ...

### PR DESCRIPTION
**Pull request by holophrastic**
...that gets "do"ed into scope.

### CODE REVIEW

**Comment by stevan** [comment]
RESPECT UR ELDERS SONNY!!!! #andgetoffmylawnwhileyouareatit

**Comment by genehack** [comment]
... pretty sure this violates some Sarbox shit, why can he even see this.

**Comment by stevan** [comment]
https://www.youtube.com/watch?v=vSivVYwKwZc

**Comment by iTommyLee** [comment]
scram, european!

**Comment by stevan** [comment]
Shouldn't you old men be in bed? Lack of sleep can't be good for your prostates.

**Comment by genehack** [comment]
@holophrastic - did you replace the 'sort by conference' completely with 'sort by author'? Because I kinda wanted to be able to do both...

**Comment by holophrastic** [comment]
What's there right now is just a refactor for the existing functionality. I can add anything else we want, I just wanted to get the data format changes in so people could go back to adding stuff.

**Comment by holophrastic** [comment]
Also, I don't quite know what you mean - the "talks" hashref is still done with conf/year/talk, it's only the directory layout that's by author (so people can just add things in their own directory and not worry about anything else).

**Pull request merged**
